#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=8
ENV_FILE=/dev/null
EVIDENCE_FILE="${EVIDENCE_FILE:-snapshot-rollback-evidence-$(date -u +%Y%m%dT%H%M%SZ).md}"

record_field() {
  printf -- '- %s: %s\n' "$1" "$2" >> "$EVIDENCE_FILE"
}

require_yes() {
  if ! confirm "$1"; then
    warn "Stopped. Resolve this gate before continuing; the evidence draft remains at $EVIDENCE_FILE."
    exit 1
  fi
}

banner "PI Coffee · linux002 snapshot rollback"

stage "Register the exact VM and maintenance window"
say "Use docs/deployment/vm-snapshot-rollback-task.md as the authoritative procedure."
warn "This is an in-place rollback of linux002. Never start a clone beside the original VM."
ask PLATFORM "Virtualization platform:"
ask HOST_NODE "Cluster or host node:"
ask VM_NAME "VM display name (expected linux002):"
ask VM_ID "Immutable platform VM ID:"
ask OPERATOR "Operator:"
ask WINDOW_UTC "Maintenance window in UTC:"
cat > "$EVIDENCE_FILE" <<EOF
## linux002 snapshot rollback evidence draft

- Generated UTC: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
EOF
record_field "Operator" "$OPERATOR"
record_field "Platform / host node" "$PLATFORM / $HOST_NODE"
record_field "VM name / immutable VM ID" "$VM_NAME / $VM_ID"
record_field "Maintenance window UTC" "$WINDOW_UTC"
require_yes "Does the platform inventory show exactly one linux002 identity and no running clone?"

stage "Capture guest, Host, Conversation, and Git baseline"
say "On linux002, complete sections A2-A5 of the task book."
step "Record hostname/FQDN/IP, machine-id hash, SSH public-key fingerprints, service user, and deployed commit."
step "Verify Host health and all three capabilities; record only non-secret host.env fields."
step "Fetch the selected settled Conversation branch and record its ID, Checkout, local SHA, and remote SHA."
step "Create /var/lib/pi-coffee-recovery-test/before-snapshot.marker."
warn "Do not paste a token, cookie, credential, host.env contents, or transcript into this wizard."
ask BASELINE_UTC "Baseline UTC:"
ask CONVERSATION_ID "Selected disposable Conversation ID:"
ask BRANCH "Conversation branch:"
ask LOCAL_SHA_BEFORE "Local HEAD before snapshot:"
ask REMOTE_SHA_BEFORE "Fetched remote SHA before snapshot:"
ask MACHINE_HASH_BEFORE "machine-id SHA-256:"
ask SSH_FP_SUMMARY_BEFORE "SSH Host Key fingerprint summary or evidence reference:"
require_yes "Did every A-stage baseline check pass and does the before-snapshot marker exist?"
printf '\n### Baseline\n\n' >> "$EVIDENCE_FILE"
record_field "Baseline UTC" "$BASELINE_UTC"
record_field "Conversation ID" "$CONVERSATION_ID"
record_field "Branch" "$BRANCH"
record_field "Local HEAD" "$LOCAL_SHA_BEFORE"
record_field "Fetched remote SHA" "$REMOTE_SHA_BEFORE"
record_field "machine-id SHA-256" "$MACHINE_HASH_BEFORE"
record_field "SSH Host Key evidence" "$SSH_FP_SUMMARY_BEFORE"
record_field "Baseline checks" "PASS"

stage "Quiesce PI Coffee and power off the guest"
say "Block new work, wait for running turns/checkpoints/transfers to finish, stop pi-coffee-host, then power off normally."
step "Confirm pi-coffee-host is inactive before poweroff."
step "Confirm the virtualization platform reports the Guest fully powered off."
require_yes "Is linux002 powered off cleanly with no Agent operation in flight?"
printf '\n### Quiesce and snapshot\n\n' >> "$EVIDENCE_FILE"
record_field "Quiesced and powered off" "PASS"

stage "Create the powered-off disk snapshot"
say "Create a snapshot of the original VM. Do not include memory and do not create a clone."
step "Suggested name: pi-coffee-t4-linux002-<UTC>."
step "Record the exact snapshot ID, disks, UTC time, and successful platform task."
ask SNAPSHOT_NAME "Snapshot name:"
ask SNAPSHOT_ID "Snapshot ID:"
ask SNAPSHOT_UTC "Snapshot creation UTC:"
require_yes "Did the powered-off disk snapshot finish successfully with memory excluded?"
record_field "Snapshot name / ID" "$SNAPSHOT_NAME / $SNAPSHOT_ID"
record_field "Snapshot creation UTC" "$SNAPSHOT_UTC"
record_field "Snapshot type" "powered-off disk snapshot; memory included=false"

stage "Boot the same VM and create post-snapshot differences"
say "Start the original VM only, start pi-coffee-host, and verify /healthz."
step "Create /var/lib/pi-coffee-recovery-test/after-snapshot.marker."
step "Optionally add one harmless settled turn to the selected disposable Conversation."
step "Confirm both before- and after-snapshot markers now exist."
require_yes "Are both markers present and is the Host healthy after the snapshot?"
printf '\n### Post-snapshot change\n\n' >> "$EVIDENCE_FILE"
record_field "Both markers observed before rollback" "PASS"

stage "Power off and perform the in-place rollback"
say "Quiesce again, stop pi-coffee-host, and power off linux002 normally."
step "Verify the VM ID and select the exact snapshot recorded in the previous stage."
step "Perform an in-place rollback; do not clone or start a second instance."
step "After the platform task succeeds, start only the restored original VM."
ask ROLLBACK_START_UTC "Rollback start UTC:"
ask ROLLBACK_END_UTC "Rollback completion UTC:"
require_yes "Did rollback of the exact VM and snapshot complete successfully?"
printf '\n### Rollback\n\n' >> "$EVIDENCE_FILE"
record_field "Rollback start / completion UTC" "$ROLLBACK_START_UTC / $ROLLBACK_END_UTC"
record_field "Platform rollback task" "PASS"

stage "Run the complete post-rollback acceptance"
say "Complete section E of the task book. Re-run identity and Host probes; do not rely on cached synced state."
step "The before marker must exist and the after marker must be absent."
step "Hostname/IP, machine-id hash, SSH fingerprints, VM ID, Gitea owner, route/token identity, and capabilities must match."
step "Re-authenticate through OAuth, restore the Conversation, then git fetch and record local and remote SHA."
step "Verify linux001 visibility and Transfer scope remain isolated."
ask MACHINE_HASH_AFTER "machine-id SHA-256 after rollback:"
ask SSH_FP_SUMMARY_AFTER "SSH Host Key fingerprint summary or evidence reference after rollback:"
ask LOCAL_SHA_AFTER "Local HEAD after rollback:"
ask REMOTE_SHA_AFTER "Fetched remote SHA after rollback:"
require_yes "Did every E-stage check pass, including marker, Host, route, credentials, Conversation, Git, and isolation?"
printf '\n### Post-rollback acceptance\n\n' >> "$EVIDENCE_FILE"
record_field "before marker exists" "true"
record_field "after marker exists" "false"
record_field "machine-id SHA-256" "$MACHINE_HASH_AFTER"
record_field "SSH Host Key evidence" "$SSH_FP_SUMMARY_AFTER"
record_field "Local HEAD" "$LOCAL_SHA_AFTER"
record_field "Fetched remote SHA" "$REMOTE_SHA_AFTER"
record_field "Host health and three capabilities" "PASS"
record_field "VM ID / Gitea owner" "linux002 / pi-coffee-t4-user2 — PASS"
record_field "Host route/token match" "PASS"
record_field "Git/API identity match" "PASS"
record_field "Conversation/history restored" "PASS"
record_field "linux001 and Transfer isolation" "PASS"

stage "Review and hand off redacted evidence"
warn "Review the draft now. It must contain no password, token, cookie, transcript, private key, environment file, or snapshot file."
if [[ "$MACHINE_HASH_BEFORE" != "$MACHINE_HASH_AFTER" ]]; then
  warn "machine-id hash changed. This run is a failure; stop pi-coffee-host and follow section 9."
  record_field "Overall result" "FAIL — machine-id hash mismatch"
  exit 1
fi
step "Attach or paste the redacted result into Gitea awangs/pi-coffee#36."
step "Keep the snapshot until T4 #36 evidence is reviewed."
step "Only then remove the two marker files; snapshot deletion is a separate administrator decision."
record_field "Overall result" "PASS pending application-owner review"
record_field "Secret-data declaration" "No password, token, cookie, transcript, private key, environment file, or snapshot file included."
printf '\n'
say "Evidence draft: $EVIDENCE_FILE"
pause "Press Enter after you have reviewed the draft location."

finish
